name: start
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth_google: ^1.3.3
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.7
  uuid: ^3.0.7
  firebase_messaging: ^15.1.6
  rxdart: ^0.27.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flutterfire_300x.png
    - assets/dash.png

